<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'; import { useI18n } from 'vue-i18n'; import { Copy, Link2, Mail, Plus, Trash2, Users } from 'lucide-vue-next'
import AppShell from '@/components/AppShell.vue'; import api from '@/api/client'; import Button from '@/volt/Button.vue'; import InputText from '@/volt/InputText.vue'; import { useWorkspacesStore } from '@/stores/workspaces'; import { useAuthStore } from '@/stores/auth'
import AlertBanner from '@/components/ui/AlertBanner.vue'; import EmptyState from '@/components/ui/EmptyState.vue'; import FormField from '@/components/ui/FormField.vue'; import PageHeader from '@/components/ui/PageHeader.vue'; import IconButton from '@/volt/IconButton.vue'; import Select from '@/volt/Select.vue'
const { t } = useI18n(); const workspaces = useWorkspacesStore(); const auth = useAuthStore(); const members = ref<any[]>([]); const email = ref(''); const role = ref('editor'); const inviteUrl = ref(''); const error = ref(''); const loading = ref(false)
async function load() { if (workspaces.activeId) members.value = (await api.get(`/workspaces/${workspaces.activeId}/members`)).data }
async function invite() { loading.value = true; error.value = ''; try { const { data } = await api.post(`/workspaces/${workspaces.activeId}/invitations`, { email: email.value || null, role: role.value, expires_in_hours: 72, max_uses: 1 }); inviteUrl.value = data.invite_url; email.value = '' } catch (cause: any) { error.value = cause.response?.data?.detail || String(cause) } finally { loading.value = false } }
async function changeRole(member: any, value: string) { try { const { data } = await api.patch(`/workspaces/${workspaces.activeId}/members/${member.id}`, { role: value }); Object.assign(member, data) } catch (cause: any) { error.value = cause.response?.data?.detail || String(cause) } }
async function remove(member: any) { if (!confirm(t('members.confirmRemove'))) return; await api.delete(`/workspaces/${workspaces.activeId}/members/${member.id}`); if (member.user.id === auth.user?.id) { await workspaces.load(); location.assign('/') } else await load() }
async function copyInvite() { await navigator.clipboard.writeText(inviteUrl.value) }
onMounted(load); watch(() => workspaces.activeId, load)
</script>
<template><AppShell><div class="mx-auto max-w-5xl px-7 py-5"><PageHeader :title="t('nav.members')" :subtitle="t('members.subtitle')" /><AlertBanner :message="error" tone="error" /><form class="surface mt-5 flex items-end gap-3 rounded-lg p-4" @submit.prevent="invite"><FormField class="flex-1" :label="t('members.email')"><InputText v-model="email" placeholder="member@example.com" /></FormField><FormField class="w-40" :label="t('members.role')"><Select v-model="role"><option v-for="value in ['admin','editor','viewer']" :key="value" :value="value">{{ t(`roles.${value}`) }}</option></Select></FormField><Button type="submit" :loading="loading"><Plus :size="16" />{{ t('workspace.invite') }}</Button></form><div v-if="inviteUrl" class="mt-3 flex items-center gap-2 rounded-lg bg-[var(--primary-soft)] p-3 text-sm text-[var(--primary)]"><Link2 :size="16" /><span class="truncate">{{ inviteUrl }}</span><IconButton class="ml-auto" :label="t('members.copy')" @click="copyInvite"><Copy :size="15" /></IconButton></div>
<div class="surface mt-4 overflow-hidden rounded-lg"><div v-for="member in members" :key="member.id" class="flex items-center gap-3 border-b border-[var(--border)] px-4 py-3 last:border-0"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-[var(--primary-soft)] font-medium text-[var(--primary)]">{{ member.user.display_name[0] }}</span><div><div class="text-sm font-medium">{{ member.user.display_name }}</div><div class="muted flex items-center gap-1 text-xs"><Mail :size="12" />{{ member.user.email }}</div></div><span v-if="member.role === 'owner'" class="ml-auto rounded-full bg-[var(--panel-subtle)] px-2.5 py-1 text-xs">{{ t('roles.owner') }}</span><Select v-else :model-value="member.role" class="ml-auto !h-8 !w-40 !text-xs" @change="changeRole(member, ($event.target as HTMLSelectElement).value)"><option v-for="value in ['admin','editor','viewer']" :key="value" :value="value">{{ t(`roles.${value}`) }}</option></Select><IconButton v-if="member.role !== 'owner'" :label="t('members.remove')" tone="danger" @click="remove(member)"><Trash2 :size="15" /></IconButton></div><EmptyState v-if="!members.length" :title="t('members.empty')" compact><template #icon><Users :size="36" /></template></EmptyState></div></div></AppShell></template>
