<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { Bot, Plus, Trash2, Wifi } from 'lucide-vue-next'
import api from '@/api/client'; import AppShell from '@/components/AppShell.vue'; import { useWorkspacesStore } from '@/stores/workspaces'; import Button from '@/volt/Button.vue'; import InputText from '@/volt/InputText.vue'
import AlertBanner from '@/components/ui/AlertBanner.vue'; import FormField from '@/components/ui/FormField.vue'; import ModalShell from '@/components/ui/ModalShell.vue'; import PageHeader from '@/components/ui/PageHeader.vue'
const { t } = useI18n(); const workspaces = useWorkspacesStore(); const items = ref<any[]>([]); const showCreate = ref(false); const saving = ref(false); const testing = ref(''); const message = ref(''); const error = ref('')
const templates: Record<string, { base_url: string; model: string }> = { OpenAI: { base_url: 'https://api.openai.com/v1', model: 'gpt-4.1-mini' }, DeepSeek: { base_url: 'https://api.deepseek.com/v1', model: 'deepseek-chat' }, Qwen: { base_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1', model: 'qwen-plus' }, Moonshot: { base_url: 'https://api.moonshot.cn/v1', model: 'moonshot-v1-8k' }, Ollama: { base_url: 'http://host.docker.internal:11434/v1', model: 'qwen3' }, vLLM: { base_url: 'http://host.docker.internal:8000/v1', model: 'default' } }
const form = ref({ name: 'OpenAI', provider_type: 'openai-compatible', base_url: templates.OpenAI.base_url, api_key: '', default_model: templates.OpenAI.model })
const canSave = computed(() => form.value.name && form.value.base_url && form.value.default_model)
async function load() { if (workspaces.activeId) items.value = (await api.get(`/workspaces/${workspaces.activeId}/models`)).data }
function useTemplate(name: string) { form.value.name = name; form.value.base_url = templates[name].base_url; form.value.default_model = templates[name].model; showCreate.value = true }
async function save() { saving.value = true; error.value = ''; try { await api.post(`/workspaces/${workspaces.activeId}/models`, { ...form.value, config: {} }); showCreate.value = false; form.value.api_key = ''; await load() } catch (cause: any) { error.value = cause.response?.data?.detail || String(cause) } finally { saving.value = false } }
async function test(item: any) { testing.value = item.id; message.value = ''; error.value = ''; try { message.value = (await api.post(`/workspaces/${workspaces.activeId}/models/${item.id}/test`)).data.message } catch (cause: any) { error.value = cause.response?.data?.detail || String(cause) } finally { testing.value = '' } }
async function remove(item: any) { if (!confirm(t('models.confirmDelete'))) return; await api.delete(`/workspaces/${workspaces.activeId}/models/${item.id}`); await load() }
onMounted(load); watch(() => workspaces.activeId, load)
</script>
<template><AppShell><div class="flex h-screen min-h-0 overflow-hidden bg-[var(--panel)]"><aside class="flex w-52 shrink-0 flex-col border-r border-[var(--border)] bg-[var(--panel)] p-3"><h1 class="px-2 py-2 text-lg font-semibold">{{ t('models.integration') }}</h1><Button class="mt-2 w-full" @click="showCreate = true"><Plus :size="16" />{{ t('models.add') }}</Button><button class="mt-5 flex h-9 items-center gap-2 rounded-md bg-[var(--primary-soft)] px-3 text-left text-sm font-medium text-[var(--primary)]"><Bot :size="16" />{{ t('models.title') }}</button><div class="muted mt-auto px-3 py-2 text-xs">OpenAI-compatible</div></aside><main class="min-h-0 min-w-0 flex-1 overflow-y-auto bg-[var(--app-bg)] p-6"><PageHeader :title="t('models.title')" :subtitle="t('models.subtitle')"><template #actions><Button variant="secondary" @click="showCreate = true"><Plus :size="16" />{{ t('models.add') }}</Button></template></PageHeader><AlertBanner :message="message" tone="success" /><AlertBanner :message="error" tone="error" />
<section v-if="items.length" class="mt-5"><h3 class="mb-3 text-sm font-semibold">{{ t('models.configured') }}</h3><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><article v-for="item in items" :key="item.id" class="surface rounded-lg p-4"><div class="flex items-start gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--primary-soft)] text-[var(--primary)]"><Bot :size="20" /></span><div class="min-w-0 flex-1"><h2 class="truncate font-semibold">{{ item.name }}</h2><p class="muted mt-1 truncate text-xs">{{ item.base_url }}</p></div></div><div class="mt-4 rounded-md bg-[var(--panel-subtle)] px-3 py-2 text-xs"><span class="muted">{{ t('models.defaultModel') }}</span><span class="ml-2 font-medium">{{ item.default_model }}</span></div><div class="mt-4 flex justify-end gap-2"><Button variant="secondary" :loading="testing === item.id" @click="test(item)"><Wifi :size="15" />{{ t('models.test') }}</Button><Button variant="ghost" @click="remove(item)"><Trash2 :size="15" /></Button></div></article></div></section>
<section class="mt-6 border-t border-[var(--border)] pt-5"><h3 class="text-sm font-semibold">{{ t('models.available') }}</h3><p class="muted mt-1 text-xs">{{ t('models.availableHint') }}</p><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><button v-for="(template, key) in templates" :key="key" class="surface card-hover min-h-32 rounded-lg p-4 text-left" @click="useTemplate(String(key))"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--primary-soft)] text-base font-bold text-[var(--primary)]">{{ String(key).slice(0, 2) }}</span><div><div class="font-semibold">{{ key }}</div><div class="muted mt-1 text-xs">{{ template.model }}</div></div></div><p class="muted mt-4 truncate text-xs">{{ template.base_url }}</p></button></div></section></main>
<ModalShell v-model="showCreate" :title="t('models.add')" max-width="max-w-2xl" form @submit="save"><div class="flex flex-wrap gap-2"><button v-for="(_, key) in templates" :key="key" type="button" class="rounded-md border border-[var(--border)] px-3 py-1.5 text-xs hover:border-[var(--primary)]" @click="useTemplate(String(key))">{{ key }}</button></div><div class="mt-4 grid grid-cols-2 gap-4"><FormField :label="t('common.name')" required><InputText v-model="form.name" required /></FormField><FormField :label="t('models.defaultModel')" required><InputText v-model="form.default_model" required /></FormField><FormField class="col-span-2" label="Base URL" required><InputText v-model="form.base_url" required /></FormField><FormField class="col-span-2" label="API Key"><InputText v-model="form.api_key" type="password" /></FormField></div><template #footer><Button type="button" variant="secondary" @click="showCreate = false">{{ t('common.cancel') }}</Button><Button type="submit" :loading="saving" :disabled="!canSave">{{ t('common.save') }}</Button></template></ModalShell></div></AppShell></template>
