<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'; import { useI18n } from 'vue-i18n'; import { Braces, FileCode2, Play, Plus, Trash2, Upload } from 'lucide-vue-next'
import AppShell from '@/components/AppShell.vue'; import api from '@/api/client'; import Button from '@/volt/Button.vue'; import InputText from '@/volt/InputText.vue'; import { useWorkspacesStore } from '@/stores/workspaces'
import AlertBanner from '@/components/ui/AlertBanner.vue'; import EmptyState from '@/components/ui/EmptyState.vue'; import PageHeader from '@/components/ui/PageHeader.vue'; import Textarea from '@/volt/Textarea.vue'
import SearchInput from '@/components/ui/SearchInput.vue'
import ModalShell from '@/components/ui/ModalShell.vue'
const { t } = useI18n(); const workspaces = useWorkspacesStore(); const items = ref<any[]>([]); const showEditor = ref(false); const saving = ref(false); const testing = ref(false); const error = ref(''); const search = ref(''); const selected = ref<any>(null); const fileInput = ref<HTMLInputElement | null>(null); const testInputs = ref('{"message":"Hello"}'); const testResult = ref<any>(null)
const form = ref({ name: '', description: '', source_code: 'def main(inputs, context):\n    return {"message": inputs.get("message", "Hello")}', entrypoint: 'main', tagsText: '' })
const filtered = computed(() => items.value.filter(item => item.name.toLowerCase().includes(search.value.toLowerCase()) || item.tags?.some((tag: string) => tag.toLowerCase().includes(search.value.toLowerCase()))))
async function load() { if (workspaces.activeId) items.value = (await api.get(`/workspaces/${workspaces.activeId}/scripts`)).data }
function newScript() { selected.value = null; testResult.value = null; form.value = { name: '', description: '', source_code: 'def main(inputs, context):\n    return {"message": inputs.get("message", "Hello")}', entrypoint: 'main', tagsText: '' }; showEditor.value = true }
async function edit(item: any) { selected.value = item; const versions = (await api.get(`/workspaces/${workspaces.activeId}/scripts/${item.id}/versions`)).data; const latest = versions[0]; form.value = { name: item.name, description: item.description || '', source_code: latest.source_code, entrypoint: latest.entrypoint, tagsText: item.tags?.join(', ') || '' }; testResult.value = null; showEditor.value = true }
async function save() { saving.value = true; error.value = ''; const payload = { name: form.value.name, description: form.value.description, tags: form.value.tagsText.split(',').map(v => v.trim()).filter(Boolean), source_code: form.value.source_code, entrypoint: form.value.entrypoint, input_schema: { type: 'object' }, output_schema: { type: 'object' } }; try { if (selected.value) await api.put(`/workspaces/${workspaces.activeId}/scripts/${selected.value.id}`, { ...payload, expected_version: selected.value.latest_version, change_note: 'Updated in script editor' }); else await api.post(`/workspaces/${workspaces.activeId}/scripts`, payload); showEditor.value = false; await load() } catch (cause: any) { error.value = cause.response?.data?.detail || String(cause) } finally { saving.value = false } }
async function upload(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; const name = file.name.replace(/\.(py|zip)$/i, ''); const formData = new FormData(); formData.append('file', file); formData.append('name', name); formData.append('entrypoint', file.name.toLowerCase().endsWith('.zip') ? 'main:main' : 'main'); saving.value = true; try { await api.post(`/workspaces/${workspaces.activeId}/scripts/upload`, formData); await load() } catch (cause: any) { error.value = cause.response?.data?.detail || String(cause) } finally { saving.value = false; input.value = '' } }
async function test() { testing.value = true; error.value = ''; try { testResult.value = (await api.post(`/workspaces/${workspaces.activeId}/scripts/${selected.value.id}/test`, { inputs: JSON.parse(testInputs.value), timeout_seconds: 30 })).data } catch (cause: any) { error.value = cause.response?.data?.detail || String(cause) } finally { testing.value = false } }
async function remove() { if (!selected.value || !confirm(t('scripts.confirmDelete'))) return; await api.delete(`/workspaces/${workspaces.activeId}/scripts/${selected.value.id}`); showEditor.value = false; await load() }
onMounted(load); watch(() => workspaces.activeId, load)
</script>
<template><AppShell><div class="px-7 py-5"><PageHeader :title="t('scripts.title')" :subtitle="t('scripts.subtitle')"><template #actions><input ref="fileInput" type="file" class="hidden" accept=".py,.zip" @change="upload"><Button variant="secondary" :loading="saving" @click="fileInput?.click()"><Upload :size="16" />{{ t('scripts.upload') }}</Button><Button @click="newScript"><Plus :size="16" />{{ t('scripts.newScript') }}</Button></template></PageHeader><AlertBanner :message="error" tone="error" /><SearchInput v-model="search" class="mt-5 w-72" :placeholder="t('common.search')" />
<div v-if="filtered.length" class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><button v-for="item in filtered" :key="item.id" class="surface card-hover rounded-lg p-4 text-left" @click="edit(item)"><div class="flex items-start gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-50 text-emerald-600 dark:bg-emerald-950/40"><FileCode2 :size="20" /></span><div class="min-w-0"><h2 class="truncate font-semibold">{{ item.name }}</h2><p class="muted mt-1 line-clamp-2 text-sm">{{ item.description || 'Python · main(inputs, context)' }}</p></div></div><div class="muted mt-5 flex justify-between border-t border-[var(--border)] pt-3 text-xs"><span>{{ t('scripts.version') }} {{ item.latest_version }}</span><span>{{ item.tags?.join(', ') }}</span></div></button></div><EmptyState v-else class="mt-16" :title="t('scripts.empty')"><template #icon><Braces :size="42" /></template></EmptyState>
<ModalShell v-model="showEditor" :title="selected ? t('scripts.edit') : t('scripts.newScript')" max-width="max-w-5xl" body-class="grid grid-cols-[minmax(0,1fr)_300px] !overflow-hidden p-0" form @submit="save"><section class="min-w-0 overflow-y-auto p-5"><div class="grid grid-cols-2 gap-3"><InputText v-model="form.name" :placeholder="t('scripts.name')" required /><InputText v-model="form.tagsText" :placeholder="t('scripts.tags')" /></div><InputText v-model="form.description" class="mt-3" :placeholder="t('common.description')" /><Textarea v-model="form.source_code" class="mt-3 h-[430px] !bg-slate-950 p-4 font-mono !text-sm !text-slate-100" spellcheck="false" /></section><aside class="overflow-y-auto border-l border-[var(--border)] bg-[var(--panel-subtle)] p-5"><h3 class="font-semibold">{{ t('scripts.test') }}</h3><p class="muted mt-1 text-xs">{{ t('scripts.testHint') }}</p><Textarea v-model="testInputs" class="mt-3 h-36 font-mono !text-xs" /><Button class="mt-3 w-full" type="button" :disabled="!selected" :loading="testing" @click="test"><Play :size="15" />{{ t('scripts.run') }}</Button><pre v-if="testResult" class="mt-4 max-h-64 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{{ JSON.stringify(testResult, null, 2) }}</pre></aside><template #footer><Button v-if="selected" class="mr-auto" type="button" variant="danger" @click="remove"><Trash2 :size="15" />{{ t('common.delete') }}</Button><Button type="button" variant="secondary" @click="showEditor = false">{{ t('common.cancel') }}</Button><Button type="submit" :loading="saving">{{ t('common.save') }}</Button></template></ModalShell></div></AppShell></template>
