<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'; import { useI18n } from 'vue-i18n'; import { useRouter } from 'vue-router'; import { Archive, RotateCcw, Save, Trash2 } from 'lucide-vue-next'
import api from '@/api/client'; import AppShell from '@/components/AppShell.vue'; import { useWorkspacesStore } from '@/stores/workspaces'; import Button from '@/volt/Button.vue'; import InputText from '@/volt/InputText.vue'
import AlertBanner from '@/components/ui/AlertBanner.vue'; import FormField from '@/components/ui/FormField.vue'; import PageHeader from '@/components/ui/PageHeader.vue'; import Textarea from '@/volt/Textarea.vue'
const { t } = useI18n(); const router = useRouter(); const workspaces = useWorkspacesStore(); const saving = ref(false); const error = ref(''); const message = ref(''); const confirmName = ref(''); const form = ref({ name: '', description: '', timezone: 'UTC', version: 1 })
const workspace = computed<any>(() => workspaces.active); const canDelete = computed(() => confirmName.value === workspace.value?.name)
function sync() { const item: any = workspace.value; if (item) form.value = { name: item.name, description: item.description || '', timezone: item.timezone || 'UTC', version: item.version } }
async function save() { saving.value = true; error.value = ''; try { const { data } = await api.patch(`/workspaces/${workspaces.activeId}`, form.value); Object.assign(workspace.value, data); form.value.version = data.version; message.value = t('settings.saved') } catch (cause: any) { error.value = cause.response?.data?.detail || String(cause) } finally { saving.value = false } }
async function archive() { const action = workspace.value.is_archived ? 'restore' : 'archive'; const { data } = await api.post(`/workspaces/${workspaces.activeId}/${action}`); Object.assign(workspace.value, data) }
async function remove() { if (!canDelete.value) return; await api.delete(`/workspaces/${workspaces.activeId}`); await workspaces.load(); const next = workspaces.items[0]; if (next) { workspaces.select(next.id); router.push(`/w/${next.id}/studio`) } else router.push('/workspaces/new') }
onMounted(async () => { await workspaces.load(); sync() }); watch(() => workspaces.activeId, sync)
</script>
<template><AppShell><div class="mx-auto max-w-4xl px-7 py-5"><PageHeader :title="t('settings.title')" :subtitle="t('settings.subtitle')" /><AlertBanner :message="message" tone="success" /><AlertBanner :message="error" tone="error" />
<form class="surface mt-5 rounded-lg p-5" @submit.prevent="save"><h2 class="font-semibold">{{ t('settings.general') }}</h2><div class="mt-4 grid gap-4"><FormField :label="t('settings.workspaceName')" required><InputText v-model="form.name" required /></FormField><FormField :label="t('common.description')"><Textarea v-model="form.description" class="h-24" /></FormField><FormField :label="t('settings.timezone')"><InputText v-model="form.timezone" /></FormField></div><div class="mt-5 flex justify-end"><Button type="submit" :loading="saving"><Save :size="15" />{{ t('common.save') }}</Button></div></form>
<section class="surface mt-5 rounded-lg border-amber-200 p-5 dark:border-amber-900"><h2 class="font-semibold">{{ t('settings.lifecycle') }}</h2><p class="muted mt-1 text-sm">{{ t('settings.archiveHint') }}</p><Button class="mt-4" variant="secondary" @click="archive"><RotateCcw v-if="workspace?.is_archived" :size="15" /><Archive v-else :size="15" />{{ workspace?.is_archived ? t('settings.restore') : t('settings.archive') }}</Button></section>
<section class="mt-5 rounded-lg border border-red-200 bg-[var(--panel)] p-5 dark:border-red-900"><h2 class="font-semibold text-red-600">{{ t('settings.danger') }}</h2><p class="muted mt-1 text-sm">{{ t('settings.deleteHint') }}</p><FormField class="mt-4 max-w-md" :label="t('settings.typeName', { name: workspace?.name })"><InputText v-model="confirmName" /></FormField><Button class="mt-4" variant="danger" :disabled="!canDelete" @click="remove"><Trash2 :size="15" />{{ t('settings.delete') }}</Button></section></div></AppShell></template>
