<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'; import { useI18n } from 'vue-i18n'; import { useRouter } from 'vue-router'
import { Bot, Clock3, FileCheck2, Plus, Tags, Workflow as WorkflowIcon } from 'lucide-vue-next'
import AppShell from '@/components/AppShell.vue'; import api from '@/api/client'; import ActionCard from '@/volt/ActionCard.vue'; import AlertBanner from '@/components/ui/AlertBanner.vue'; import Button from '@/volt/Button.vue'; import InputText from '@/volt/InputText.vue'; import { useWorkspacesStore } from '@/stores/workspaces'
import EmptyState from '@/components/ui/EmptyState.vue'; import FormField from '@/components/ui/FormField.vue'; import ModalShell from '@/components/ui/ModalShell.vue'; import PageHeader from '@/components/ui/PageHeader.vue'; import Textarea from '@/volt/Textarea.vue'
import FilterDropdown from '@/components/ui/FilterDropdown.vue'; import SearchInput from '@/components/ui/SearchInput.vue'
const { t } = useI18n(); const router = useRouter(); const workspaces = useWorkspacesStore(); const items = ref<any[]>([]); const search = ref(''); const creating = ref(false); const createError = ref(''); const showCreate = ref(false); const type = ref('all'); const status = ref('all'); const newestFirst = ref(true); const form = ref<{ name: string; description: string; app_type: string; template_id: string | null }>({ name: '', description: '', app_type: 'workflow', template_id: null })
const filtered = computed(() => items.value.filter(item => item.name.toLowerCase().includes(search.value.toLowerCase()) && (type.value === 'all' || item.app_type === type.value) && (status.value === 'all' || (status.value === 'published') === Boolean(item.published_version_id))).sort((a, b) => (new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()) * (newestFirst.value ? 1 : -1)))
const typeOptions = computed(() => ['all','workflow','chat'].map(value => ({ value, label: value === 'all' ? t('studio.all') : t(`studio.${value}`) })))
const statusOptions = computed(() => ['all','published','draft'].map(value => ({ value, label: value === 'all' ? t('studio.allStatuses') : t(`studio.${value}`) })))
async function load() { if (workspaces.activeId) items.value = (await api.get(`/workspaces/${workspaces.activeId}/workflows`)).data }
function selectAppType(value: string) { form.value.app_type = value; if (value !== 'workflow') form.value.template_id = null }
function selectTemplate(templateId: string | null) { form.value.app_type = 'workflow'; form.value.template_id = templateId; if (templateId && !form.value.name) form.value.name = t('studio.englishExamTemplate') }
async function create() { creating.value = true; createError.value = ''; try { const { data } = await api.post(`/workspaces/${workspaces.activeId}/workflows`, form.value); showCreate.value = false; router.push(`/w/${workspaces.activeId}/workflows/${data.id}`) } catch (cause: any) { createError.value = cause.response?.data?.detail || String(cause) } finally { creating.value = false } }
onMounted(load); watch(() => workspaces.activeId, load)
</script>
<template><AppShell><div class="px-7 py-5"><PageHeader :title="t('studio.title')" :subtitle="t('studio.subtitle')"><template #actions><Button @click="showCreate = true"><Plus :size="16" />{{ t('studio.newApp') }}</Button></template></PageHeader>
<div class="mt-5 flex flex-wrap items-center gap-2"><FilterDropdown v-model="type" :options="typeOptions" /><FilterDropdown v-model="status" :options="statusOptions"><template #icon><Tags :size="14" /></template></FilterDropdown><Button variant="secondary" @click="newestFirst = !newestFirst"><Clock3 :size="14" />{{ newestFirst ? t('studio.recent') : t('studio.oldest') }}</Button><SearchInput v-model="search" class="ml-1 w-64" :placeholder="t('common.search')" /></div>
<div v-if="filtered.length" class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4"><ActionCard v-for="item in filtered" :key="item.id" class="min-h-40 p-4" @click="router.push(`/w/${workspaces.activeId}/workflows/${item.id}`)"><div class="flex gap-3"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[var(--primary-soft)] text-violet-600"><Bot v-if="item.app_type === 'chat'" :size="21" /><WorkflowIcon v-else :size="21" /></span><div class="min-w-0"><h2 class="truncate font-semibold">{{ item.name }}</h2><p class="muted mt-1 line-clamp-2 text-sm">{{ item.description || t('studio.noApps') }}</p></div></div><div class="muted mt-7 flex items-center justify-between border-t border-[var(--border)] pt-3 text-xs"><span>v{{ item.draft_version }} · {{ new Date(item.updated_at).toLocaleDateString() }}</span><span :class="item.published_version_id ? 'text-emerald-600' : ''">{{ item.published_version_id ? t('studio.published') : t('studio.draft') }}</span></div></ActionCard></div><EmptyState v-else class="mt-16" :title="t('studio.noResults')"><template #icon><WorkflowIcon :size="42" /></template></EmptyState>
<ModalShell v-model="showCreate" :title="t('studio.newApp')" form @submit="create"><AlertBanner :message="createError" tone="error" /><div class="grid grid-cols-2 gap-2"><ActionCard class="p-3" :active="form.app_type === 'workflow'" @click="selectAppType('workflow')"><WorkflowIcon :size="18" /><div class="mt-2 text-sm font-medium">{{ t('studio.workflow') }}</div></ActionCard><ActionCard class="p-3" :active="form.app_type === 'chat'" @click="selectAppType('chat')"><Bot :size="18" /><div class="mt-2 text-sm font-medium">{{ t('studio.chat') }}</div></ActionCard></div><section v-if="form.app_type === 'workflow'" class="mt-4"><h3 class="mb-2 text-xs font-semibold">{{ t('studio.startFrom') }}</h3><div class="grid grid-cols-2 gap-2"><ActionCard class="p-3" :active="form.template_id === null" @click="selectTemplate(null)"><WorkflowIcon :size="18" /><div class="mt-2 text-sm font-medium">{{ t('studio.blankWorkflow') }}</div></ActionCard><ActionCard class="p-3" :active="form.template_id === 'english_exam_answer_filler'" @click="selectTemplate('english_exam_answer_filler')"><FileCheck2 :size="18" /><div class="mt-2 text-sm font-medium">{{ t('studio.englishExamTemplate') }}</div><p class="muted mt-1 text-[10px] leading-4">{{ t('studio.englishExamTemplateHint') }}</p></ActionCard></div></section><FormField class="mt-4" :label="t('common.name')" required><InputText v-model="form.name" required /></FormField><FormField class="mt-4" :label="t('common.description')"><Textarea v-model="form.description" class="h-20" /></FormField><template #footer><Button type="button" variant="secondary" @click="showCreate = false">{{ t('common.cancel') }}</Button><Button type="submit" :loading="creating">{{ t('common.create') }}</Button></template></ModalShell></div></AppShell></template>
